### ISSUE TITLE
DropDownListView:(DropDownListView *)dropdownListView didSelectedIndex:(NSInteger)anIndex  not calling!

### ISSUE THREAD

**Issue by ismaiI1** [kiran5232/KDropDownMultipleSelection#7]
when i touch the button DropDownListView showing but when i clicked the tableviewcell not returning the delegate method. why?

**Comment by KiranPatelSpaceo** [comment]
I think you are using Gesture in your code. so Config tableview gesture and your gesture .
Try following delegate 
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
  
  if ([touch.view.superview isKindOfClass:[DropDownViewCell class]] {
      return NO;
  }
  return YES;

}

**Comment by ismaiI1** [comment]
Yes, i am using Gesture. where should i add this code?

edit : i find the solution. i add this code to my TapGestureRecognizer.

[tap setCancelsTouchesInView:NO];
